name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Rulează la fiecare 6 ore
  workflow_dispatch:  # Permite rularea manuală

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  
      
